apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  labels:
    app: demo-app

spec:
  containers:
    - name: new-demo-container
      image: mcr.microsoft.com/dotnet/samples:aspnetapp
      ports:
        - containerPort: 8080