apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app

spec:
  template:
    metadata:
      name: demo-app-pod
      labels:
        app: demo-app

    spec:
      containers:
        - name: new-demo-container
          image: mcr.microsoft.com/dotnet/samples:aspnetapp
          ports:
            - containerPort: {{ .Values.containerPort }}
  replicas: {{ .Values.replicasNumber }}
  selector: 
    matchLabels: 
      app: demo-app
  