apiVersion: v1
kind: Service
metadata: 
  name: demo-app-service
spec: 
  type: NodePort
  ports: 
    - targetPort: {{ .Values.port }}
      port: {{ .Values.port }}
      nodePort: {{ .Values.containerPort }}
  selector:
    app: demo-app